name: "Development"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:

jobs:
  development:
    uses: integrated-wellness-inc/.github/.github/workflows/development.yml@main
